/** Frases rotativas para el inicio del participante (dashboard). */
export const FRASES_IDOLOS = [
  'La camiseta de la Selección está por encima de todos.',
  'Jugar para Argentina es lo más grande que hay.',
  'La Selección no se explica: se siente.',
  'Somos Argentina. Siempre hay que creer.',
  'La camiseta argentina no se negocia.',
  'Con esta camiseta se juega hasta el último segundo.',
  'Ser argentino es sufrir, creer y volver a levantarse.',
  'Muchachos, ahora nos volvimos a ilusionar.',
  'Esta Copa es para todos los argentinos.',
  'La Selección es de todos.',
  'Esta camiseta tiene historia, gloria y presión.',
  'El que no sufre, no entiende lo que es ser argentino.',
  'Hoy vibraron todos los corazones celestes y blancos.',
  'Yo muero por esta camiseta.',
  'Ganar con Argentina vale doble.',
  'Con Argentina se llora distinto.',
  'No es solo fútbol: es Argentina.',
  'La tercera llegó cuando más la necesitábamos.',
  'De las finales perdidas al cielo de Qatar.',
  'Esta Selección entendió que también había que saber sufrir.',
  'Argentina hizo feliz a un país entero.',
  'El Mundial no lo ganó un equipo: lo ganó un país.',
  'De la mano de Leo Messi, todos la vuelta vamos a dar.',
  'Argentina, tierra de Di Stéfano, Maradona y Messi.',
  'La Selección es eso: los que juegan, los que alientan y los que lloran desde casa.',
  'La celeste y blanca no se usa: se honra.',
  'La bandera también juega.',
  'Argentina se lleva en el pecho, no en la espalda.',
  'Donde juega Argentina, late un país entero.',
  'La Selección es el abrazo de todos los argentinos.',
  'No hay camiseta más pesada ni más hermosa que la argentina.',
  'Cuando juega Argentina, no juega un equipo: juega una nación.',
  'La celeste y blanca une lo que nada más puede unir.',
  'Argentina no se rinde, Argentina insiste.',
  'La patria también se defiende con una pelota.',
  'Con la Selección, el corazón juega antes que los pies.',
  'Cada estrella en el escudo es una alegría del pueblo.',
  'La Argentina futbolera vive en cada grito de gol.',
  'La Selección es la bandera hecha equipo.',
  'Ser argentino es mirar al cielo y ver celeste y blanco.',
]
