/** Nombres en PRODEX (español) → nombre en football-data.org para buscar escudo. */
export const TEAM_CREST_ALIASES = {
  sudafrica: 'South Africa',
  'south africa': 'South Africa',
  canada: 'Canada',
  canadá: 'Canada',
  alemania: 'Germany',
  germany: 'Germany',
  paraguay: 'Paraguay',
  francia: 'France',
  france: 'France',
  suecia: 'Sweden',
  sweden: 'Sweden',
  'paises bajos': 'Netherlands',
  'países bajos': 'Netherlands',
  holanda: 'Netherlands',
  netherlands: 'Netherlands',
  marruecos: 'Morocco',
  morocco: 'Morocco',
  espana: 'Spain',
  españa: 'Spain',
  spain: 'Spain',
  'estados unidos': 'United States',
  usa: 'United States',
  'united states': 'United States',
  belgica: 'Belgium',
  bélgica: 'Belgium',
  belgium: 'Belgium',
  brasil: 'Brazil',
  brazil: 'Brazil',
  japon: 'Japan',
  japón: 'Japan',
  japan: 'Japan',
  'costa de marfil': 'Ivory Coast',
  'ivory coast': 'Ivory Coast',
  noruega: 'Norway',
  norway: 'Norway',
  mexico: 'Mexico',
  méxico: 'Mexico',
  argentina: 'Argentina',
  'cabo verde': 'Cape Verde Islands',
  'cape verde': 'Cape Verde Islands',
  'cape verde islands': 'Cape Verde Islands',
  australia: 'Australia',
  egipto: 'Egypt',
  egypt: 'Egypt',
  suiza: 'Switzerland',
  switzerland: 'Switzerland',
  'bosnia-herzegovina': 'Bosnia-Herzegovina',
  'bosnia herzegovina': 'Bosnia-Herzegovina',
  inglaterra: 'England',
  england: 'England',
  croacia: 'Croatia',
  croatia: 'Croatia',
  uruguay: 'Uruguay',
  colombia: 'Colombia',
  chile: 'Chile',
  ecuador: 'Ecuador',
  peru: 'Peru',
  perú: 'Peru',
  portugal: 'Portugal',
  italia: 'Italy',
  italy: 'Italy',
  turquia: 'Turkey',
  turkey: 'Turkey',
  'corea del sur': 'South Korea',
  'south korea': 'South Korea',
  'arabia saudita': 'Saudi Arabia',
  'saudi arabia': 'Saudi Arabia',
  senegal: 'Senegal',
  ghana: 'Ghana',
  nigeria: 'Nigeria',
  camerun: 'Cameroon',
  cameroon: 'Cameroon',
  tunisia: 'Tunisia',
  tunez: 'Tunisia',
  túnez: 'Tunisia',
  argelia: 'Algeria',
  algeria: 'Algeria',
  iran: 'Iran',
  qatar: 'Qatar',
  panama: 'Panama',
  panamá: 'Panama',
  'nueva zelanda': 'New Zealand',
  'new zealand': 'New Zealand',
  escocia: 'Scotland',
  scotland: 'Scotland',
  austria: 'Austria',
  'republica checa': 'Czechia',
  'rep. checa': 'Czechia',
  'república checa': 'Czechia',
  czechia: 'Czechia',
  curazao: 'Curaçao',
  curaçao: 'Curaçao',
  haiti: 'Haiti',
  haití: 'Haiti',
  jordania: 'Jordan',
  jordan: 'Jordan',
  uzbekistan: 'Uzbekistan',
  uzbequistán: 'Uzbekistan',
  irak: 'Iraq',
  iraq: 'Iraq',
}

export function normTeamCrestKey(name) {
  return String(name || '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/\s+/g, ' ')
}

export function apiTeamNameForCrest(displayName) {
  const key = normTeamCrestKey(displayName)
  return TEAM_CREST_ALIASES[key] || displayName
}
